
set nocompatible

set autoread
set autowrite
set backspace=indent,eol,start
set clipboard=unnamed
set cursorline
set encoding=utf-8
set expandtab
set foldmethod=marker
set guicursor=a:block
set hidden
set nohlsearch
set ignorecase
set incsearch
set mouse=a
set number
set path=.,~/.config/**,~/lib,~/doc/**,~/rep/rbs/**,,
set relativenumber
set ruler

set shiftwidth=4
set showcmd
set showmode
set smartcase
set nosmarttab
set softtabstop=-1
set noswapfile
set textwidth=0
set wildmenu


syntax on
filetype plugin indent on

let mapleader=" "

map <leader>h :set hlsearch!<CR>
map <leader>w :write<CR>
map <leader>r :set wrap!<CR>

map <M-Left> :bprev<CR>
map <M-Right> :bnext<CR>

map <C-M-Left> <C-W>h
map <C-M-Down> <C-W>j
map <C-M-Up> <C-W>k
map <C-M-Right> <C-W>l

map <C-S-M-Left> :vertical :resize -1<CR>
map <C-S-M-Down> :resize -1<CR>
map <C-S-M-Up> :resize +1<CR>
map <C-S-M-Right> :vertical :resize +1<CR>

