
set nocompatible

set encoding=utf-8
set hidden
set noswapfile

set guicursor=a:block
set mouse=a
set showmode
set showcmd
set ruler
set wildmenu

syntax on
filetype plugin indent on

set number
set relativenumber

set backspace=indent,eol,start
set ignorecase
set smartcase
set hlsearch
set incsearch
map g/ :nohlsearch<CR>

set expandtab
set nosmarttab
set shiftwidth=4
set softtabstop=-1
set textwidth=100

set path=.
set path+=~/.config/**
set path+=~/lib
set path+=~/doc/**
set path+=~/rep/rbs/**
set path+=,

